FROM golang:latest
MAINTAINER "Tim Fall <tim@hashicorp.com>"

RUN cd $GOPATH
RUN go get github.com/mitchellh/packer
WORKDIR $GOPATH/src/github.com/mitchellh/packer
RUN bash -c make

ENTRYPOINT ["$GOPATH/bin/packer"]
